name: Testing the GitHub Pages publication

on:
  push:
    branches: 
      - master
    
jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    # Specify the target branch (optional)
    - uses: helaili/jekyll-action@2.0.4
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
      with:
        target_branch: 'output'
